images: []

steps:
  - id: "Fetch Secrets"
    name: "gcr.io/cloud-builders/gcloud"
    waitFor: []
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud secrets versions access latest --secret=npm-token > npm-token.txt
       '

  - id: "Debug"
    waitFor:
      - "Fetch Secrets"
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - '
          echo THE THING $(cat npm-token.txt)
        '

  - id: "Build Publisher"
    waitFor: []
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "build"
      - "."
      - "-t"
      - "publisher"

  - id: "Publish"
    waitFor:
      - "Fetch Secrets"
      - "Build Publisher"
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - '
         docker run
         --env NPM_TOKEN=$(cat npm-token.txt)
         publisher
          npm publish; exit 0
        '
